# IO: all determined by the sysfs interface!

# Entities
entities:
  push_buttons:
    - name: office
      io: shady/di_1_01
    - name: office_up
      io: shady/di_1_02
    - name: office_down
      io: shady/di_1_03

  lights:
    - name: office
      io: shady/ro_2_01

  covers:
    - name: office
      motor_up: shady/ro_2_02
      motor_down: shady/ro_2_03

# Automations
automations:
  lights:
    - name: office
      push_button: office
      light: office

  covers:
    - name: office
      push_button_up: office_up
      push_button_down: office_down
      cover: office
